In [1]:
# 도형그리기 

import cv2 
import numpy as np

In [2]:
# 빈 스케치북 만들기 
# 세로 480 * 가로 640, 3channel(rgb)에 해당하는 스케치북 만들기

img = np.zeros((480,640,3), dtype = np.uint8)
img[:] = (255,200,0)  #전체 공간을 흰색으로 채우기
print(img)

#opencv에서는 bgr임 순서를 잘 기억하자

cv2.imshow('img',img)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[[255 200   0]
  [255 200   0]
  [255 200   0]
  ...
  [255 200   0]
  [255 200   0]
  [255 200   0]]

 [[255 200   0]
  [255 200   0]
  [255 200   0]
  ...
  [255 200   0]
  [255 200   0]
  [255 200   0]]

 [[255 200   0]
  [255 200   0]
  [255 200   0]
  ...
  [255 200   0]
  [255 200   0]
  [255 200   0]]

 ...

 [[255 200   0]
  [255 200   0]
  [255 200   0]
  ...
  [255 200   0]
  [255 200   0]
  [255 200   0]]

 [[255 200   0]
  [255 200   0]
  [255 200   0]
  ...
  [255 200   0]
  [255 200   0]
  [255 200   0]]

 [[255 200   0]
  [255 200   0]
  [255 200   0]
  ...
  [255 200   0]
  [255 200   0]
  [255 200   0]]]


In [3]:
# grayscale

img = np.zeros((480,640), dtype = np.uint8)

#0~255
img[:] = 255  #전체 공간을 흰색으로 채우기
# img[100:200,100:200] = 50  #일부 공간을 흰색으로 채우기
print(img)


cv2.imshow('img',img)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [4]:
# 일부영역 색칠하기 

img = np.zeros((480,640,3), dtype = np.uint8)
img[100:200,100:200] = (255,0,0)
# img[세로,가로]

cv2.imshow('img',img)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [5]:
# 도형그리기(직선)
# 직선의 종류 
# 1. cv2.LINE_4 : 상하좌우 4방향으로 연결된 선
# 2. cv2.LINE_8 : 대각선을 포함한 8방향으로 연결된 선(기본값)
# 3. cv2.LINE_AA : 부드러운 선

In [8]:
img = np.zeros((480,640,3), dtype = np.uint8)

# 색이나 굵기 먼저 설정하기
color = (0,255,255) #bgr   YELLOW
thickness = 3   #두께


# cv2.line(어디에 그릴지, (x,y 어디부터), (x,y 어디까지))
cv2.line(img, (50,100), (400,50), color, thickness, cv2.LINE_8)
cv2.line(img, (50,200), (400,150), color, thickness, cv2.LINE_4)
cv2.line(img, (50,300), (400,250), color, thickness, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
# 원 그리기 

img = np.zeros((480,640,3), dtype = np.uint8)

# 색이나 굵기 먼저 설정하기
color = (255,255,0) #bgr   옥색
radius = 50     # 반지름
thickness = 3   #두께

cv2.circle(img, (200,100), radius, color, thickness, cv2.LINE_AA) # 속이 빈 원
cv2.circle(img, (400,100), radius, color, cv2.FILLED, cv2.LINE_AA) # 꽉 찬 원
cv2.circle(img, (550,100), radius, color, -1, cv2.LINE_AA) # 꽉 찬 원
# 그릴 위치, 원의 중심점, 반지름, 색깔, 두께, 선의종류

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
# 사각형

img = np.zeros((480,640,3), dtype = np.uint8)

# 색이나 굵기 먼저 설정하기
color = (0,255,0) #bgr  초록색
thickness = 3   #두께

cv2.rectangle(img, (100,100),(200,200),color,thickness,cv2.LINE_AA)
cv2.rectangle(img, (100,100),(200,200),color,-1,cv2.LINE_AA)
# 그릴 위치, 왼쪽 위 좌표, 오른쪽 아래좌표, 색깔, 두께, 선의 종류

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
# 다각형 

img = np.zeros((480,640,3), dtype = np.uint8)

# 색이나 굵기 먼저 설정하기
color = (0,0,255) #bgr  빨간색
thickness = 3   #두께

pts1 = np.array([[100,100],[200,100],[100,200]]) # 삼각형
pts2 = np.array([[200,100],[300,100],[300,200]])

# cv2.polylines(img,[pts1],True, color,thickness,cv2.LINE_AA)
# cv2.polylines(img,[pts2],True, color,thickness,cv2.LINE_AA)
# cv2.polylines(img,[pts1,pts2],True, color,thickness,cv2.LINE_AA)

# 그릴 위치, 좌표변수, isClosed 여부,  색깔, 두께, 선의 종류

pts3 = np.array([[[100,100],[200,100],[100,200]],[[200,100],[300,100],[300,200]]])
cv2.fillPoly(img,pts3,color,cv2.LINE_AA)
# 그릴 위치, 좌표변수, 색, 선 종류


cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()